name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install assertpy
        python -m pip install key-generator
        python -m pip install pyhamcrest
        python -m pip install parameterized
        python -m pip install pytest
    - name: Test with unittest
      run: |
         python -m unittest discover tests/
